### ISSUE TITLE
Can't access elements on SKStoreProductViewController without resorting to SLStaticElement

### ISSUE THREAD

**Issue by MaxGabriel** [inkling/Subliminal#10]
I'm testing an app that shows an `SKStoreProductViewController`. So far, I haven't found a good way to access any elements inside it without resorting to `SLStaticElement`. I've [added code to the sample app to demonstrate this](https://github.com/MaxGabriel/SubliminalRemoteVC/blob/master/Example/Integration%20Tests/STModalTest.m). 

The first test confirms that a regular modal view controller and cancel button can be accessed. The second test confirms that using `SLStaticElement` allows me to access the `cancel` button. The final test confirms that you can't access the cancel button just by doing `SLButton *cancelButton = [SLButton elementWithAccessibilityLabel:@"Cancel"]`.

The accessibility inspector confirms the button's accessibility label is Cancel. I've also tried the accessibility identifier, but no luck there.

I'm pretty sure that `SKStoreProductViewController` is one of those Remote View Controllers than runs in another process, so I figure that may be the problem? I suppose to test this I should test against another Remote VC like `MFMailComposeViewController`. Wondered if anyone's run into this yet, and has a better solution than using the static elements.

**Comment by wearhere** [comment]
Hey Max, kudos to you for figuring this stuff out! The `SKStoreProductViewController` is, like you suggest, a remote VC. You can see this if you pause the app in the debugger with the controller up:

```
(lldb) po [[UIWindow keyWindow] recursiveDescription]
$0 = 0x073114a0 <UIWindow: 0x8d17800; frame = (0 0; 320 480); layer = <UIWindowLayer: 0x8d17900>>
   | <UIView: 0xf312bb0; frame = (0 20; 320 460); layer = <CALayer: 0xf312c10>>
   |    | <_UISizeTrackingView: 0x8b71660; frame = (0 0; 320 460); clipsToBounds = YES; autoresize = W+H; layer = <CALayer: 0x8b71740>>
   |    |    | <_UIRemoteView: 0x8b71870; frame = (0 0; 320 480); userInteractionEnabled = NO; layer = <CALayerHost: 0x8b71a70>>
```

And there the view hierarchy dead-ends.

This sort of thing is, unfortunately, where `SLStaticElement` comes in--`SLElement` can't traverse, and thus match, objects within that remote view hierarchy. But `SLStaticElement` will work: there _are_ accessibility elements in the remote view, and UIAutomation can see them:

![screen shot 2013-06-08 at 3 22 57 am](https://f.cloud.github.com/assets/110000/627377/26b596da-d026-11e2-948b-eeada6677d91.png)

That view was generated by creating a new UIAutomation script using the Automation trace template (not Subliminal's template) and playing back `UIATarget.localTarget().logElementTree()` after I'd brought up the modal store controller. So, to tap on the "Reviews" tab, say, you'd read from the hierarchy

``` javascript
UIATarget.localTarget().frontMostApp().mainWindow().scrollViews()[0].webViews()[0].buttons()["Reviews\n"].tap();
```

(The nicest way to generate static representations is usually to record yourself interacting with the app, but for whatever reason, UIAutomation can't do this for remote hierarchies--recording a tap on the "Reviews" tab prints out a "raw" event like

``` javascript
target.frontMostApp().mainWindow().scrollViews()[0].webViews()[0].tapWithOptions({tapOffset:{x:0.51, y:0.09}});
```

(That is, an event agnostic as to the actual element tapped.))

One saving grace of remote views is that they're generally well-structured--so it should be possible for us Subliminal contributors to abstract the relevant static representations behind `SLStaticElement` subclasses. You could make an `SLStoreProductView` element (not set on that name) which offered an API like `-switchToTab:(SLStoreProductViewTab)tab`; invoking that method with `SLStoreProductViewTabReviews` would cause the JavaScript above to be evaluated.

I think that it would be a very worthwhile addition to Subliminal to implement `SLStaticElement` subclasses for the common remote views/their sub-elements--it would be ideal for 3rd-party devs to never have to think about how UIAutomation represents elements.

**Comment by MaxGabriel** [comment]
Thanks for the feedback Jeff. So I think that Instruments can handle recording interaction with some remote view controllers, as most interactions worked fine with [`MFMailComposeViewController`](http://oleb.net/blog/2012/10/more-on-remote-view-controllers/). Your solution sounds like the best approach for `SKStoreProductViewController`. Closing the issue
