### ISSUE TITLE
Cannot run tests in a Test class in a specified order

### ISSUE THREAD

**Issue by rgonzo** [inkling/Subliminal#101]
I have tried to order my tests numerically so that they run in a specified order but when I execute my tests, the test run does not adhere to the numerical naming convention. How do I specify which test runs?

**Comment by wearhere** [comment]
Hi @rgonzo, there's currently no mechanism for specifying an order in which to run test cases. Our concern about adding such dependencies would be that they might make the tests brittle: see [this comment](https://github.com/inkling/Subliminal/pull/56#issuecomment-22574447) and [my response](https://github.com/inkling/Subliminal/pull/56#issuecomment-22584515), in a discussion about ordering tests. I'd be curious to hear your use case though and if you think you have a solution to my worries.

**Comment by wearhere** [comment]
Closing this issue pending further comment.
