### ISSUE TITLE
Tests will randomly hang at different points during test run

### ISSUE THREAD

**Issue by rgonzo** [inkling/Subliminal#104]
When running my test suite through Xcode or through the command-line, I have noticed that the tests will sit and hang for no apparent reason. I have no clue why the test will suddenly hang.  The test will essentially hang forever or until I stop it. I have about 19 lengthy tests that are supposed to run but it gets to the 3rd or 4th or 5th test and then it just randomly stops. 

By the way, when I run each test individually, they all will completely run when executing the solo test. 

I wish the test would just error or the entire suite would bomb out but that just doesnt happen and instead I get a test run that last forever. Please help! I would be more than willing to give you logs but unfortunately all I have are the instruments logs which are not useful for debugging.

**Comment by wearhere** [comment]
Hey @rgonzo, sorry for the late response. Can you tell us anything more about the point at which the tests hang? For instance, is your app hung, or the tests? You could tell by trying to interact with your app while it's running. If the tests are hung, at which method calls are they hung?

You might also use the debugger to figure out what's going on when a hang occurs. See the last answer [here](https://github.com/inkling/Subliminal#debugging-tests) to attach the debugger. After you've done that, just press "Pause" in Xcode like you normally would. Then you can see what each thread (main, or test) are doing in the Debug Navigator on the left side of Xcode.

**Comment by wearhere** [comment]
Closing pending further comment.
