### ISSUE TITLE
Subliminal's tests can't be run on iOS 5.

### ISSUE THREAD

**Issue by aegolden** [inkling/Subliminal#12]
The testing targets have deployment targets set to iOS 6. Also, some target-specific bugs:
### Unit tests

Bug: f764e6c38d194384003f9ce075e45cffa7dd1e95. Proposed solution: https://github.com/inkling/Subliminal/commit/f764e6c38d194384003f9ce075e45cffa7dd1e95#commitcomment-3382208.
### Integration tests

Bug: they use iOS 6-only APIs in a few places. The troublesome calls are:

``` objc
- (void)registerClass:(Class)cellClass forCellReuseIdentifier:(NSString *)identifier NS_AVAILABLE_IOS(6_0);
```

and

``` objc
- (id)dequeueReusableCellWithIdentifier:(NSString *)identifier forIndexPath:(NSIndexPath *)indexPath NS_AVAILABLE_IOS(6_0);
```

**Comment by wearhere** [comment]
#11 addresses this partially (by fixing the deployment target issue).
