### ISSUE TITLE
Add tagging system to SLTests

### ISSUE THREAD

**Issue by jazzychad** [inkling/Subliminal#126]
Something we would like to achieve with Subliminal is to be able to run certain subsets of tests which are "related" (whatever that means for the particular use-case).

Just as we have `[SLTest allTests]`, it might be nice to have something like `[SLTest testsWithTags:@["tagOne", "tagTwo", "tagThree]]` to run tests that identify themselves as having one of the specified tags.

I was thinking of adding a readonly `NSArray *tags` property to SLTest which would return an array of tags it belongs to (default behavior in SLTest would return nil).

In `+[SLTest testsWithTags:]` it would determine which tests to run (also keeping in mind focused tests) based on the tags of tests returned from `+allTests`.

This could be useful for setting up separate Jenkins jobs which exercise only certain classes of tests (for example, Jenkins could pass in certain defined macro symbols which the developer will use to determine which test sets get compiled in at build time in the app delegate), or for a developer to very quickly 'focus' some set of tests w/o having to manually 'focus_' each class file.

I am happy to code this up and send a pull-request. I think I know how to add this pretty quickly given my current understanding of the system.

Thoughts about this feature/approach?

**Comment by jazzychad** [comment]
Actually I think `tags` would have to be a class method on each test class for ease of implementation (and it will play nicer w/ the current system that `allTests` uses).

**Comment by jazzychad** [comment]
Ok, I have a working version of this in a local branch. I've written some unit tests to go with it and it's working as expected. I'll clean up the code and add the appledoc comments in the morning.

**Comment by wearhere** [comment]
Superseded by #127.
