### ISSUE TITLE
Wiki improvement

### ISSUE THREAD

**Issue by volbap** [inkling/Subliminal#137]
Guys, on the wiki, below this section:

Running the Example App

You forgot to add the following steps:
`git submodule init`
`git submodule update`

Otherwise I was getting "OCMock.h file not found" error.

Cheers.

**Comment by wearhere** [comment]
Thanks for the report @pablolvillar. I'm a bit curious because OCMock isn't a dependency of the example project itself, but rather Subliminal's own tests--so theoretically you shouldn't need to initialize this dependency unless you wanted to work on Subliminal itself.

When you opened the example project, did you by chance try to build the "_Subliminal_ Integration Tests" scheme? Then you'd get the error--but I just tried the instructions and the "Integration Tests" scheme worked fine for me.

**Comment by volbap** [comment]
No problem. I remember I did.

Also, in this part:
"To apply this file to your target, expand Subliminal's project reference in your navigator pane, then drag the Integration Tests.xcconfig file into the base level of your Integration Tests group."
It wasn't quite clear for me whether I had to copy the file or just drag the reference. As at first I copied it, it was leading the project not to compile since the xcconfig wasn't working. Then I realized I just had to drag it. It'd be nice to have that clarified there.

Cheers.

**Comment by volbap** [comment]
Yes, you were right. It was because I was working with Subliminal itself. Sorry for that.

Still I couldn't make Subliminal work on my project :( I did follow all the steps and I could make it build (profile), but when instruments starts I get "An error occurred while trying to run the script." (referencing SLTerminal.js)

Any ideas on what could be going on?
Thanks in advance.

**Comment by wearhere** [comment]
Just made some changes to the README per your feedback, thanks.

Regarding that error, have you tried resetting the simulator and then restarting Instruments (i.e. quitting it and then selecting "profile" from Xcode again)? Also what OS, version of Xcode, and simulator type are you using?

**Comment by volbap** [comment]
Hey there. I did the whole setup process again and it seems it's been fixed. But now it hangs with just one log that says "Tests are starting up...", while the script status is Stopped.

I did add the lines on the app delegate to make the framework detect my tests and I do have a class which inherits from SLTests and has tests like "- (void)testLoginSuccessful".

I'm looking forward to see it working on my project but even though I feel like I'm almost there I'm always getting something that stops me. :/ 

Any ideas on this one? (Note: I restarted both Xcode, Simulator and its Contents and Settings a lot of times).

Thank you guys, I appreciate your feedback.

**Comment by wearhere** [comment]
Hey @pablolvillar I lost the thread of this--did you ever get this to work? Xcode 5.1 might have improved things somewhat. Sorry to hear you were having such troubles.

**Comment by wearhere** [comment]
Hi @pablolvillar I'm going to close this just to keep the project's issues a bit cleaner, but please do comment here or reach out in [our chat room](https://gitter.im/inkling/Subliminal) if you're willing and able to provide any additional information. Once again I'm sorry to hear that you weren't able to get off to a good start with the framework.
