### ISSUE TITLE
Can Subliminal use the new -w flag to select a device using instruments?

### ISSUE THREAD

**Issue by MaxGabriel** [inkling/Subliminal#143]
I noticed in the [Xcode 5.1 release notes](https://developer.apple.com/library/mac/releasenotes/DeveloperTools/RN-Xcode/Introduction/Introduction.html) that `instruments` now lets you specify a device: 

> The `instruments` command-line tool now supports specifying the simulator SDK and device type using the `-w` flag. To see a list of the supported simulator configurations as well as attached devices, execute `instruments -s devices` in a Terminal window. (14996865)

I know that Subliminal jumps through several hoops to achieve this right now—is this new feature sufficient to replace the disabling/enabling of other SDKs and such?

This isn't really an issue per se as the current approach works for me—I just wanted to let you know about this if you hadn't seen it already.

**Comment by wearhere** [comment]
Thanks for reminding me about this! This does indeed appear to resolve http://openradar.appspot.com/radar?id=3107401 (meaning no more disabling/enabling SDKs!) as well as http://openradar.appspot.com/radar?id=3106401 (meaning we wouldn't have to [override the `TARGETED_DEVICE_FAMILY` at build](https://github.com/inkling/Subliminal/blob/master/Supporting%20Files/CI/subliminal-test#L414)). If we could verify a work-around for http://openradar.appspot.com/14135016, we could even remove the need for `subliminal-test` to be run with the login password.

We should adopt this as soon as Travis picks up Xcode 5.1 (https://github.com/travis-ci/travis-ci/issues/2051).

**Comment by wearhere** [comment]
We should also investigate if maybe this new `instruments` can install applications on devices, which would remove our need to use the `MobileDevice` framework (#75).

**Comment by wearhere** [comment]
`instruments 5.1` still cannot install applications on devices, which is a bit of a shame. (But not too much, because we would want to do a clean install of the app, and I'd doubt that `instruments` would uninstall applications.)

**Comment by wearhere** [comment]
I'm tagging this 1.1 because it would be super nice to launch to a bunch of new people with no SDK manipulation and maybe even no login password requirement (i.e. if we can confirm pre-authorization works). Discussion on https://github.com/travis-ci/travis-ci/issues/2051 seems to suggest that Travis will support 5.1 before we would be launching 1.1 anyway.

**Comment by wearhere** [comment]
The README will need to be updated to reflect the requirement of Xcode 5.1 when this goes in. The README should also note that it _is_ still possible to support iOS 5.1 using Xcode 5.1, if you run Mountain Lion and [manually install the iOS 5.1 simulator](http://stackoverflow.com/a/22494536/495611).

**Comment by wearhere** [comment]
I've got a local branch using the `-w` flag--just need [travis-ci/travis-ci#2501](https://github.com/travis-ci/travis-ci/issues/2051) to be resolved before I can put it up.

Also, I can confirm that the old (pre-Mavericks) method of pre-authorizing `instruments` from travis-ci/travis-ci#1292 works. If the later technique in that thread or something similar works for Mavericks, then we can remove the need for the login password altogether!

**Comment by MaxGabriel** [comment]
Nice @wearhere!

**Comment by wearhere** [comment]
Ok I've made the change locally to completely deprecate the `--live` and `-login_password` options. When https://github.com/travis-ci/travis-ci/issues/2051 is resolved, I'll put a pull request up for this and also update [the wiki](https://github.com/inkling/Subliminal/wiki/Continuous-Integration) to describe how instruments may be "pre-authorized" as described on https://github.com/travis-ci/travis-ci/issues/1292.

**Comment by MaxGabriel** [comment]
[Travis CI is now running Mavericks](http://blog.travis-ci.com/2014-04-15-xcode-51-ios-71-osx-109/)

**Comment by wearhere** [comment]
Thanks Max! Testing now.
