### ISSUE TITLE
Can creating a new info.plist file be removed from the installation process?

### ISSUE THREAD

**Issue by MaxGabriel** [inkling/Subliminal#144]
It seems like `Integration Tests-Info.plist` file that's added as part of the installation process isn't necessary to use Subliminal (if I'm wrong about this, just ignore this issue). However, a paragraph of instructions and a screenshot are devoted to making sure that it exists. The README goes on to explain how the xcconfig file specifies the path to this plist, and then another screenshot is devoted to deleting a build setting to make the xcconfig file take affect.

Additionally, having two Info.plist files means that you need to keep them in sync, so e.g. when you add a custom font to your main target's plist, you would also need to add it to your Integration Tests target's plist.

Could instead the README recommend that you delete the generated `<target name> copy-Info.plist` file, and that you use the "Choose Info.plist File..." button to select the plist your main target uses? That would solve the syncing problem and would mean you don't have to fiddle with moving the plist file to a different folder and updating Xcode's reference to it.

![screenshot 2014-03-23 11 16 27](https://f.cloud.github.com/assets/1274145/2494102/55d280c6-b2b7-11e3-8783-56729de8b1bd.png)

One downside is that if the xcconfig file were to no longer give the path to the Info.plist, that would be a breaking change for people currently relying on it. One option is to leave this setting in the xcconfig file and to just change the README instructions. The xcconfig file's plist path setting wouldn't take affect if the user selected the plist path manually. 

Alternatively, the xcconfig file could just drop the plist path setting. As far as breaking changes go, its not a big one, as there will be a straightforward compiler error about the problem (additionally, it won't affect people who copied the xcconfig file to their project instead of added it as a reference)

Edit: I guess the same question goes for Product Name? I didn't look into that one.

**Comment by wearhere** [comment]
:+1: (more comments on #145).

Also filed #146 per your suggestion.
