### ISSUE TITLE
Remove the instructions about editing "Product Name" from the README.

### ISSUE THREAD

**Issue by wearhere** [inkling/Subliminal#146]
If the user leaves it as the default setting after duplicating their main target, `<name of main target> copy`, that's a bit silly but it doesn't really matter.

When we edit the `README`, we shouldn't modify the `xcconfig` file so as not to break existing installations (though it would be nice to add a comment about the setting being maintained for historical reasons). The `xcconfig` setting won't take effect unless the user deletes the default setting.

**Comment by MaxGabriel** [comment]
#145 implements this, so this can be closed

**Comment by wearhere** [comment]
Ah yes, thanks.
