### ISSUE TITLE
Dragging in the xcconfig file as a reference crashes Xcode

### ISSUE THREAD

**Issue by MaxGabriel** [inkling/Subliminal#154]
The README says:

> Subliminal provides an `xcconfig` file to configure the rest of your target's 
> settings. To apply this file to your target, expand Subliminal's project reference 
> in your navigator pane, then drag the `Integration Tests.xcconfig` file into the 
> base level of your Integration Tests group (don't copy the file, just drag the reference).

However, when I don't use the copy option, Xcode crashes.

![xcconfigreference](https://cloud.githubusercontent.com/assets/1274145/2539218/fbf29d4a-b5c5-11e3-93ce-494223bc50a6.png)

Xcode version: Version 5.1 (5B130a)
OS Version: Mavericks 10.9.2

Potential workaround is to just recommend copying the file across?

**Comment by ominiom** [comment]
I have the same problem. Dragging `Integration Tests.xcconfig` directly from the Finder into the Project Navigator worked for me.

**Comment by MaxGabriel** [comment]
@ominiom That workaround works for me too; good find.

**Comment by wearhere** [comment]
This appears to be a bug newly introduced in Xcode 5.1. Thanks @MaxGabriel and @ominiom, I've amended the README to incorporate @ominiom's workaround.
