### ISSUE TITLE
Screencast link broken

### ISSUE THREAD

**Issue by MaxGabriel** [inkling/Subliminal#16]
The [current link](https://vimeo.com/67765518) to the screencast is broken. I searched Vimeo and found [this one](http://vimeo.com/67771344), but it seemed identical.

**Comment by wearhere** [comment]
Thanks for pointing that out, @MaxGabriel. I originally put the screencast up on my personal Vimeo account and then we later uploaded it to Inkling's account and I took my copy down. I'll update the link along with some other things in the README later today.
