### ISSUE TITLE
Add contributing guidelines to Subliminal.

### ISSUE THREAD

**Issue by wearhere** [inkling/Subliminal#166]
To include:
- How to get started (e.g. fork the repo, install Subliminal as a developer)
- What tests (unit, integration) are necessary for changes
- How to run the tests

A WIP is on [`jeff/update_docs`](https://github.com/inkling/Subliminal/commit/80392e06a607170c10973fbf3dbf05a57c8257cf) though it's out of date with regard to Subliminal's installation process and some of the links are broken.

**Comment by MaxGabriel** [comment]
Hey Jeff, do you think I could work on this? I'm pretty sure you'd have to take over to fill in alot of  details, but I could fill in the broad strokes from your WIP. This is just the last ticket needed for 1.1 and Travis CI claims to be updating this week, so I could do something basic for 1.1 if you wanted.

**Comment by wearhere** [comment]
Hey thanks @MaxGabriel. Yes, you drafting the guidelines would help me focus on getting the other PRs merged--and it would definitely be good to have a contributor's POV too.

In addition to the broad points above, I've made some comments on the WIP commit pointing out areas to update. Feel free to put up revisions for comment as you go.

**Comment by wearhere** [comment]
The points above are all about "making changes"--but a link to the guidelines will appear whenever someone goes to open an issue too (as shown [here](https://github.com/blog/1184-contributing-guidelines)), so it would also be useful to have a "filing issues" section to describe how to write up a good bug report etc.

Eventually, that is--I don't think it's strictly necessary for 1.1 (I'd rather have more contributors than more bug reports ;). I bring it up just because I'd eventually ask your thoughts on that topic--you've done a really nice job preparing issues with steps to repro and test projects.
