### ISSUE TITLE
Erroneous incompatible pointer types warning when installing w/ Cocoapods

### ISSUE THREAD

**Issue by MaxGabriel** [inkling/Subliminal#169]
When installing with Cocoapods I get this warning in two places (`SLTestController` and `SLTerminal`):

SLTestController.m:254:15: 

Incompatible pointer types initializing 'NSString *__strong' with an expression of type 'CGPathRef' (aka 'const struct CGPath *')

which is caused by the following code:

``` objc
NSString *userDirectoryPath = [[[[NSFileManager defaultManager] URLsForDirectory:NSLibraryDirectory inDomains:NSUserDomainMask] lastObject] path];
```

(The compiler is thinking that the `path` selector is the one from `CAKeyFrameAnimation`, based on the documentation it pulls up when option clicking).

Fixing this warning is super trivial—I just add a cast to `(NSURL *)`. Is that solution OK? I've tried to figure out what the root cause of why this warning shows up when installing with Cocoapods but not normally, but I haven't come up with anything.

**Comment by wearhere** [comment]
That solution sounds fine. I'm also surprised it doesn't warn all the time since this is a [general problem](http://stackoverflow.com/questions/1997482/cant-figure-out-warning-incompatible-objective-c-types) with Objective-C. Does Cocoapods change the project's warnings?

**Comment by MaxGabriel** [comment]
I mean, it isn't using Subliminal's Xcodeproj files so it does have its own settings for warnings, but I can't figure out which setting is causing this even when going through and turning them off 1 at a time.

**Comment by wearhere** [comment]
No worries. We can revisit later if manual/Cocoapods installations diverge further.
