### ISSUE TITLE
Subliminal's internal assertions are disabled in Cocoapods installs.

### ISSUE THREAD

**Issue by wearhere** [inkling/Subliminal#187]
Due to the combination of https://github.com/CocoaPods/Xcodeproj/pull/53 and Profile build phases defaulting to the Release build configuration, Subliminal's internal assertions will be disabled by default. Searching for `NSAssert` in the project, it looks like most assertions are designed to verify our internal functionality or assumptions about UIAutomation, but there are some--like [this](https://github.com/inkling/Subliminal/blob/master/Sources/Classes/SLTestController+AppHooks.m#L90)--that verify correct usage of Subliminal. Enabling these assertions would be helpful to users.

Cocoapods' assumption that users would _normally_ not want assertions enabled in Release is pretty sensible IMO--it's only libraries like us that are used while Profiling that will run afoul of this, so I don't think it's fair to ask them to change. If we wanted to work around this, it would be by getting users to change the Profile configuration over to Debug ([like this](https://github.com/inkling/Subliminal/wiki/Debugging-Tests#how-can-i-use-the-debugger-while-running-tests)). We could ask them to do this [during install](https://github.com/inkling/Subliminal/wiki/Create-the-Integration-Tests-Target); or when they went to report an issue ([here](https://github.com/inkling/Subliminal/blob/master/CONTRIBUTING.md#bug-reports)).

Is the added complexity of the above changes worth it?

**Comment by MaxGabriel** [comment]
Hm, so far I've been unsuccessful at coming up with a workaround at the Podspec level. Trying to set the macro back to 0 led to a bunch of warnings about redefining a macro. I also tried `UNDEF`ing it in the PCH file, but that didn't work (I felt like that should work so I must be misunderstanding something here...). If such a workaround existed, it would just apply to the Integration Tests target and thus would be safe to add.

I lean towards setting the Profile configuration to Debug during install. During the issue filing process is just too late, as the user would have already gone through unnecessary pain. IMO, its pretty simple to change the configuration, and anyone who wants to use the debugger has to do it anyway, so its not much added work. 

One disadvantage to this approach is that if the Integration Tests scheme isn't shared, each developer needs do to this.

**Comment by wearhere** [comment]
Closed by advising users to set the configuration to Debug [during install](https://github.com/inkling/Subliminal/wiki/Create-the-Integration-Tests-Target#cleanup).

**Comment by wearhere** [comment]
p.s. thanks for investigating the workarounds @MaxGabriel.
