### ISSUE TITLE
SLTextField isn't tappable

### ISSUE THREAD

**Issue by justinseanmartin** [inkling/Subliminal#201]
I was debugging an issue yesterday and I believe it is the same as described here:

http://stackoverflow.com/questions/23838808/how-can-i-make-an-sltextfield-tappable

I debugged it for a while, did some playing around with the UIAutomation JavaScript being generated, and found a patch that fixed the issue.  The accessibility hierarchy being generated was:

UIWindow -> STTableView (our subclass) -> UITableViewCellScrollView -> SQTextField (our subclass)

However, it seems like the accessibility hierarchy that worked from instruments was:

UIWindow -> STTableView -> SQTextField

I have a patch that fixes the behavior I was seeing, but I'm not sure what other side effects it might have (otherwise I'd just open a PR). Also, I can't tap on the text controls in iOS6 (with or without my patch), so I excluded modifying the behavior on that platform.

Patch: https://github.com/justinseanmartin/Subliminal/commit/e8cc1e5e2d0d92d38f7f232120eafa3a08d11091

**Comment by justinseanmartin** [comment]
I've opened a PR with a corresponding integration test case: https://github.com/inkling/Subliminal/pull/202

**Comment by wearhere** [comment]
Did #202 resolve this @justinseanmartin?

**Comment by justinseanmartin** [comment]
Yes, this issue is now fixed in master.

**Comment by wearhere** [comment]
:thumbsup:
