### ISSUE TITLE
TextField under ScrollView/TableView/TableCell not tappable

### ISSUE THREAD

**Issue by ghost** [inkling/Subliminal#210]
Below is a hierarchy of elements that I've been trying to find but couldn't get it to work. To add more detail, the element seems to be "seen" by the isValidorVisible method; however is not "tappable" and gives the consequent failure.

```
UIAWindow: name:UIWindow: 0x10bc37010 rect:{{0, 0}, {320, 568}}
UIAScrollView: name:TPKeyboardAvoidingScrollView: 0x10bba1360 rect:{{0, 20}, {320, 568}}
UIATableView: name:UITableView: 0x10d865200 value:rows 1 to 3 of 3 rect:{{1, 172}, {320, 132}}
UIATableCell: name:UITextField: 0x10bb9b060 value: rect:{{1, 172}, {320, 44}}
UIATextField: name:UITextField: 0x10bb9b060 value:User ID rect:{{21, 179}, {248, 30}}
UIATextField: name:User ID value:User ID rect:{{21, 179}, {248, 30}}
```

I've also created a sample application here: https://github.com/mrsamuelkim/Subliminal/tree/master/Simple%20App

Help would be appreciated! Thanks.

**Comment by justinseanmartin** [comment]
Please move the test under https://github.com/mrsamuelkim/Subliminal/tree/master/Integration%20Tests/Tests. 

It should be able to be run by launching the "Subliminal Integration Tests" target for Subliminal.xcodeproj. Prefix the test function with "focus_" to have only that one be run.

**Comment by ghost** [comment]
Test has been moved to ../Tests/

**Comment by justinseanmartin** [comment]
You need to add a reference for xLoginTests.m in the xcodeproj file. Please verify that you can run the Integration Test target of Subliminal.xcodeproj to verify that your test is runnable. See SLButtonTest for a simple example.

**Comment by ghost** [comment]
I've realized I'm having this problem only when the app is built using .storybaord. I don't see an easy way to integrate my project into Subliminal.xcodeproj.

**Comment by wearhere** [comment]
You actually don't need to add the test to Subliminal itself--putting up a sample project that uses Subliminal, and adding the test to the sample project's Integration Tests target, works just fine. :) Thanks for putting the sample up! 

To get the project's tests running, it looks like you have to add "TPKeyboardAvoiding" as a pod: https://github.com/mrsamuelkim/Subliminal/pull/1. But I can repro the failure now.

**Comment by ghost** [comment]
@wearhere, thank you! @justinseanmartin, too. 

We have two controller views currently in one screen. One main screen and another on top segued by a container. I believe that is making some complications to the hierarchy--idk, frankly.

**Comment by wearhere** [comment]
Ok,I'm pretty sure that #202 did fix this issue. The reason you don't see the fix is because the sample project uses Subliminal 1.1, which doesn't have the fix.

If you make this change:

``` diff
diff --git a/Simple App/Podfile b/Simple App/Podfile
index 7b78c6a..c34e761 100644
--- a/Simple App/Podfile    
+++ b/Simple App/Podfile    
@@ -1,7 +1,7 @@
 platform :ios, '7.1'

 target :'Integration Tests' do
-  pod 'Subliminal'
+  pod 'Subliminal', :head
   pod 'TPKeyboardAvoiding'
 end
```

And run `pod install`, then the sample project's tests will pass. Can you confirm in your real app too @mrsamuelkim? To make sure there's not any other complications.

**Comment by ghost** [comment]
Awesome. Verified. updating the Podfile fixed the problem. Thanks a lot @wearhere and @justinseanmartin!
