### ISSUE TITLE
Warning when overwriting -setUp instead of -setUpTest

### ISSUE THREAD

**Issue by KrauseFx** [inkling/Subliminal#224]
Since you're doing a lot of swizzling right now, it wouldn't be much extra work.

When I create a new test with Xcode, it automatically uses the default template and creates -setUp method. (Also I'm used to using - setUp)

It would be great, if there would be a compiler warning (or error) shown when setUpTest is not implemented, but setUp is.

**Comment by wearhere** [comment]
Hm, are you using this template to create a new test?

![screen shot 2014-06-25 at 1 24 33 pm](https://cloud.githubusercontent.com/assets/110000/3391113/dfc0a310-fca6-11e3-8440-b369d457109c.png)

It sounds like you might be using Xcode's regular unit test template. Subliminal's should stub out `-setUpTest` for you.

The reason we use "setUpTest", by the way, is that our method behaves differently from OCUnit's `-setUp`: it's only executed once per test, whereas `-setUp` is called once per test case.

Documentation about Subliminal's template is [here](https://github.com/inkling/Subliminal/wiki/Writing-Tests), and about the difference between `-setUpTest` and `-setUp` [here](http://inkling.github.io/Subliminal/Documentation/Classes/SLTest.html#//api/name/setUpTest). Do you have any suggestions how we might make these topics clearer?

**Comment by wearhere** [comment]
(Also: do you think that information is sufficient, or do you think it would still be worth checking for `-setUp` being implemented?)

**Comment by KrauseFx** [comment]
I wasn't using this template for my previous tests but didn't notice it's not the same method right at the beginning.

My suggestion is to display a compiler warning, when only the wrong method is implemented. It's a nice to have, since as you mentioned, this behaviour is documented. Just something I spent a little time until I figured it out

**Comment by wearhere** [comment]
Showing a warning wouldn't be too difficult, but I can't think of how we might easily let the user _disable_ that warning--to let them implement `-setUp` if they wanted, even without implementing `-setUpTest`. Altogether, I think I'd rather stick with the cues we have: the template and documentation. Thanks for the suggestion, though!
