### ISSUE TITLE
Xcode DP5 warning: Implicit conversion from enumeration type 'enum CGImageAlphaInfo' to different enumeration type 'CGBitmapInfo' (aka 'enum CGBitmapInfo')

### ISSUE THREAD

**Issue by MaxGabriel** [inkling/Subliminal#23]
The existing code is:

```
CGContextRef context = CGBitmapContextCreate(pixels, columns, rows, 8, 4 * columns, rgbColorSpace, kCGImageAlphaPremultipliedLast);
```

I'm not really familiar with this depth of CG, but I saw that SDWebImage does something like this? 

```
CGContextRef context = CGBitmapContextCreate(pixels, columns, rows, 8, 4 * columns, rgbColorSpace, kCGBitmapByteOrderDefault | kCGImageAlphaPremultipliedLast);
```

It might be a bug on Apple's part. From the documentation it seems that you should be able to pass just the `kCGImageAlphaPremultipliedLast`.

**Comment by aegolden** [comment]
I think the way to do this is to change the last argument to `kCGBitmapAlphaInfoMask & kCGImageAlphaPremultipliedLast`.  It's basically the same trick as is being used in SDWebImage:  `kCGBitmapAlphaInfoMask` is of type `CGBitmapInfo` so this should silence the compiler warning, and the `&` ensures that the actual value passed to `CGBitmapContextCreate` is unchanged; however I think `kCGBitmapAlphaInfoMask & kCGImageAlphaPremultipliedLast` is the way Apple intends these constants to be used.

The documentation for all this is unfortunately not very clear, but I think the idea is that you can create multiple different masks and `|` them together.  For example, you could also do `(kCGBitmapAlphaInfoMask & kCGImageAlphaPremultipliedLast) | (kCGBitmapByteOrderMask & kCGBitmapByteOrderDefault)`.  And if you were inspecting the bitmap info of that bitmap you could do tests like `(bitmapInfo & kCGBitmapAlphaInfoMask) == kCGImageAlphaPremultipliedLast` and `(bitmapInfo & kCGBitmapByteOrderMask) == kCGBitmapByteOrderDefault`.

**Comment by aegolden** [comment]
Pull request here: https://github.com/inkling/Subliminal/pull/24

**Comment by MaxGabriel** [comment]
Thanks that was a great explanation
