### ISSUE TITLE
"SLWaitUntilTrue" can be confused with "SLAssertTrueWithTimeout".

### ISSUE THREAD

**Issue by wearhere** [inkling/Subliminal#236]
As reported by @lisbakke in Gitter:

> some of the guys didn't realize that SLWaitUntilTrue required you to listen to the return value. Their fault for not reading the docs, but the name of the function is misleading -- I think the expectation is that it might assert after the timeout.

Perhaps we should rename it to `SLIsTrueWithTimeout`?

**Comment by lisbakke** [comment]
Personally, I think that is a good proposed name.

**Comment by wearhere** [comment]
Ok cool. Replacing this with two actionable issues: #241 and #242.
