### ISSUE TITLE
Add support for identifying alerts by message.

### ISSUE THREAD

**Issue by ghost** [inkling/Subliminal#246]
`SLAlert` currently only matches alerts by title, but alerts don't actually have to have titles. Therefore it would be nice to add support for matching alerts by text (the "message" provided to `-[UIAlertView initWithTitle:message:delegate:cancelButtonTitle:otherButtonTitles:]`).

This would involve adding an `+alertWithMessage:` constructor to `SLAlert`, and modifying `-[SLAlert isEqualToUIAAlertPredicate]` to compare messages if the `SLAlert` had not been initialized with a title.

**Comment by wearhere** [comment]
Thanks @mrsamuelkim! I've made the description a bit more specific. I agree this would be a good addition to the framework.

**Comment by ghost** [comment]
I was able to fix this issue by making a temporary edits to `-isEqualToUIAAlertPredicate` so it points to the message instead of the `alert.name()`. For me, it was `alert.scrollViews()[0].staticTexts()[1].value()`.

@wearhere, would you prefer to check title first and if it wasn't initialized then go to the message? or would you want to separate the methods?

**Comment by wearhere** [comment]
Title first, then message (and asserting if both are `nil`) sounds good.

Btw is it `staticTexts()[1]` even if there's no title? I thought I saw then that there would be only one static text element. To be safe we should probably do something like

``` js
var textElements = alert.scrollViews()[0].staticTexts().toArray();
if (textElements.length > 0) {
   // assumes _message_ has been formatted into this snippet somehow
   return message === textElements[textElements.length - 1].value();
} else {
   return NO;
}
```

**Comment by ghost** [comment]
Ah, makes sense to do that! I was just doing a quick change for verification reasons. Thanks!

**Comment by wearhere** [comment]
I take it that you tried out #248 @mrsamuelkim? I'd like to have its merger close this issue (via the "resolves" tag), but thanks for following up!

**Comment by ghost** [comment]
@wearhere, ah, sorry about that!

**Comment by ghost** [comment]
Oops. Sorry about that--again!
