### ISSUE TITLE
"WebKit Threading Violation" error on Xcode6 and iOS8

### ISSUE THREAD

**Issue by hongkai** [inkling/Subliminal#247]
I am trying to run subliminal test on Mavericks + Xcode6 beta4 and iOS8 and keep getting the "WebKit Threading Violation" below.  (The same app runs fine with subliminal-test on Xcode 5 and iOS7 device/simulator.) 

Has anyone else encounter this issue?

```
Successfully installed the application on the device.

Relaunching tests...

ERROR: 2014-07-31 12:49:51.686 instruments[43821:4703] WebKit Threading Violation - initial use of WebKit from a secondary thread.

The target application appears to have died
```

**Comment by wearhere** [comment]
This issue appears to be inherent to `instruments`, not to the Automation template/Subliminal: I can get it even when executing `instruments -s devices`. But I'm not sure what triggers this--I've been running `instruments` for a while testing various things (within a single session) and only "recently" has it started appearing.

It also, as of beta 5, doesn't cause `instruments` to abort, at least.

Did you file a Radar? If not I'll file one. It's a bit of a shame not knowing what causes the message to appear but we might as well report it.

**Comment by cybertk** [comment]
Any update?

**Comment by cybertk** [comment]
See https://groups.google.com/forum/#!msg/calabash-ios/DapUUgOxihA/zwB3A4_0rBQJ

**Comment by KrauseFx** [comment]
This is definitely related to the `Instruments` and not `Subliminal`. Ran into the same issue.

**Comment by flogehring** [comment]
I saw the same issue and it disappeared after I removed my Xcode plugins from `~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/`

**Comment by runloop** [comment]
I have this issue and removing my plugins did not help.

**Comment by mokagio** [comment]
> This is definitely related to the Instruments and not Subliminal. Ran into the same issue.

Same here. :+1:

**Comment by MJanach** [comment]
I am getting the same error with these specs:
Appium v1.3.6
Yosemite 10.10.2
Xcode 6.2(6C131e)
iOS 8.2(12D508)

**Comment by bayamp** [comment]
Did anyone figure out solution for this? I'm facing the same issue.
