### ISSUE TITLE
Class tag NSSet could also include superclasses (up to SLTest)

### ISSUE THREAD

**Issue by justinseanmartin** [inkling/Subliminal#252]
Just a thought, but in our case, we are tagging our classes much in the same way that we're organizing our class hierarchies. It might be nice if SLTest derivative classes also tagged themselves with their superclasses.

**Comment by wearhere** [comment]
Oh oops, classes not inheriting tags was not by design. Will fix for 1.2.

**Comment by justinseanmartin** [comment]
I was referring more to for the default "tags" that you're assigning for the name of the class.  You could do it like (off the cuff):

```
    Class classIter = [self class];
    while (classIter != [SLTest class]) {
        [set addObject:NSStringFromClass(classIter)];
        classIter = [classIter superclass];
    }
```

**Comment by wearhere** [comment]
Gotcha.
