### ISSUE TITLE
Cocoapods Integration

### ISSUE THREAD

**Issue by MaxGabriel** [inkling/Subliminal#29]
I got Subliminal working through Cocoapods this morning.

Advantages:
1. Easy to keep subliminal up to date without using git submodules
2. Never see Subliminal's own Unit/Integration tests, which is confusing
3. When you install Subliminal you won't get all of its schemes added to your project
4. Since Cocoapods uses it's own `.xcconfig` file, I don't think it's possible to use Subliminal's `.xcconfig` file in tandem. 

Here's a fork of Subliminal with a [working Podspec](https://github.com/MaxGabriel/Subliminal). 
Here's an [example project](https://github.com/MaxGabriel/SubliminalPodExample) using Subliminal through Cocoapods.

My Todo list:
- [x] Test that CI still works through Cocoapods UPDATE: CI works great, have it running for a project at work
- [x] Test on a computer that has never had Subliminal installed before
- [x] Don't add unnecessary files within `Supporting Files/Xcode` like the xcconfig file or schemes.
- [x] Remove comments from Subliminal podspec
- [x] Add author emails to Podspec. @wearhere would that just be yours?
- [x] Add Cocoapods specific documentation. I was going to make a wiki page for this since the README is pretty crowded. **Update**: See the [proposed docs](https://github.com/MaxGabriel/Subliminal/wiki/Install-with-Cocoapods). I mostly rearranged the existing documentation, made a few small edits, and added the section about configuring the Podfile.

**Comment by wearhere** [comment]
I am fully on board with creating a podspec. :+1: We found Wed. that Subliminal's installation instructions don't anticipate how messy people's project files can get. Part of working around that is giving them a packaged solution like Cocoapods. I had actually begun using [your guide](http://maxgabriel.github.io/companyAndTheCocoapod/) to create a podspec but working with you directly is even better! :grin: 

Can you put up a work-in-progress pull request so I can make some comments on your spec?

Some feedback on what you have above:
- Yeah, Subliminal's `.xcconfig` file is unnecessary with Cocoapods.
- You're right that Subliminal's schemes are unnecessary to a regular user of the framework... what if a user decided they wanted to start working on Subliminal? Though I actually don't know how that would work in general--vs. if they were using a submodule, where they could just change the endpoint to their fork. Would they just have to uninstall Subliminal and reinstall it as a submodule? (Or work on Subliminal independent from its use in their project?)
- Yeah, you can put my email, jeff@inkling.com.

**Comment by MaxGabriel** [comment]
Oh, my guide is more targeted for frameworks, static libraries and bundles rather than open-source projects, so it probably wouldn't be helpful. 

Will put up a PR. 

Re bullet 2: Cocoapods asks that the code you give the user doesn't include tests, documentation, example projects, etc. so the schemes wouldn't be useful anyway. If they want to make modifications to Subliminal, AFAIK the Cocoapods way would be to fork the Subliminal repo and within their Podfile use syntax like `pod 'Subliminal', :git => 'https://github.com/MaxGabriel/Subliminal.git'` to specify their repo.

**Comment by dmur** [comment]
:+1:
