### ISSUE TITLE
Link in slStringByEscapingForJavaScriptLiteral 404s

### ISSUE THREAD

**Issue by MaxGabriel** [inkling/Subliminal#36]
The comment in the implementation of `slStringByEscapingForJavaScriptLiteral` 404s:

```
// Escape sequences taken from here: http://ecma262-5.com/ELS5_HTML.htm#Section_7.8.4
```

[Clickable](http://ecma262-5.com/ELS5_HTML.htm#Section_7.8.4)

http://ecma262-5.com/ gives a 'Web Page Unavailable'  -- not sure what to read from that. 

[This page](http://www.ecma-international.org/ecma-262/5.1/#sec-7.8.4) may be equivalent to what that link was pointing to.

**Comment by wearhere** [comment]
Yes, looks like they moved it. Thanks for finding the new link.
