### ISSUE TITLE
Cannot find table cell with custom layout

### ISSUE THREAD

**Issue by phatmann** [inkling/Subliminal#48]
I have a UITableViewCell that uses a custom layout with a UILabel inside of it. When I do logElementTree on the main window, I see the cell in the list and it says its name is "foo". However, `[SLElement elementWithAccessibilityLabel:@"foo"]` does not find the cell. Manually setting the accessibilityLabel of the cell itself did not help. On the other hand, if I manually set the cell's accesibilityIdentifier to "foo" and use `[SLElement elementWithAccessibilityIdentifier:@"foo"]` that works fine.

I can try to provide sample code and/or a failing test if you need more info.

**Comment by wearhere** [comment]
Hey @phatmann, some code to replicate your table view cell would be great, thanks. I can't tell offhand how this might differ from the existing table view test cases in `SLElementMatchingTest`.

**Comment by wearhere** [comment]
`-[SLElementMatchingTest testCannotMatchIndividualChildLabelsOfTableViewCell]` looks closest to your situation--it verifies that cells derive their accessibility labels from their child `UILabels`' text. It successfully tests that two labels are combined into one; when I modified the `SLElementMatchingCell` it uses to only have one label, that still seemed alright.

**Comment by phatmann** [comment]
I have been unable to create a test case that fails in the Subliminal test suite, after many attempts.

So I decided to take a different tack, and I turned on script logging for the failing test in my app. I was surprised what I saw.

Here is the test:

``` objective-c
- (void)testSearch
{
    [[SLTerminal sharedTerminal] setScriptLoggingEnabled:YES];

    SLElement *searchField = [SLElement elementWithAccessibilityLabel:@"Search Text"];
    [searchField tap];

    [[SLKeyboard keyboard] typeString:@"shirt"];
    [NSThread sleepForTimeInterval:1];

    SLElement *suggestionCell = [SLElement elementWithAccessibilityLabel:@"SHIRT"];
    [suggestionCell tap];
}
```

And here is the log:

```
script:9: SLTerminal.SLAssertTrueWithTimeout(function() { return (SLTerminal.SLElementIsTappable(UIATarget.localTarget().frontMostApp().elements()['UIWindow: 0xae18230'].elements()['TFSSearchTextField: 0x13147ee0'])); }, 0.25, 4.99896)
script:10: UIATarget.localTarget().frontMostApp().elements()['UIWindow: 0xae18230'].elements()['TFSSearchTextField: 0x13147ee0'].tap()
script:11: SLTerminal.SLAssertTrueWithTimeout(function() { return (UIATarget.localTarget().frontMostApp().keyboard().isValid()); }, 0.25, 5)
script:12: SLTerminal.SLAssertTrueWithTimeout(function() { return (SLTerminal.SLElementIsTappable(UIATarget.localTarget().frontMostApp().keyboard())); }, 0.25, 4.89792)
script:13: UIATarget.localTarget().frontMostApp().keyboard().typeString('shirt')
script:14: SLTerminal.SLAssertTrueWithTimeout(function() { return (SLTerminal.SLElementIsTappable(UIATarget.localTarget().frontMostApp().elements()['UIWindow: 0xae18230'].elements()['TFSSearchTextField: 0x13147ee0'].elements()['WebAccessibilityObjectWrapper: 0x13c67fa0'])); }, 0.25, 4.99825)
script:15: UIALogger.logError('(null):0: Unexpected exception occurred ***SLUIAElementNotTappableException*** for reason: Element \'<SLElement description:\"SHIRT\">\' is not tappable.');
```

So when my test calls:

``` objective-c
SLElement *suggestionCell = [SLElement elementWithAccessibilityLabel:@"SHIRT"];
[suggestionCell tap];
```

The script being sent is:

```
UIATarget.localTarget().frontMostApp().elements()['UIWindow: 0xae18230'].elements()['TFSSearchTextField: 0x13147ee0'].elements()['WebAccessibilityObjectWrapper: 0x13c67fa0']
```

For some reason Subliminal is not looking for an element named "SHIRT" but is instead using the previously found element (the TFSSearchTextField). Any idea how this could happen? Of course I am happy to dig in and debug, but I wanted to check with you first to see if the answer jumped out at you.

**Comment by wearhere** [comment]
Thanks for your research @phatmann, this is very interesting. I note that Subliminal isn't trying to tap _exactly_ the same element the second time--it's identifying a `WebAccessibilityObjectWrapper` inside the text field rather than the text field itself. (Those sorts of objects are used by `UIWebView` to represent text etc., and I know that `UITextView` uses a `UIWebView` to render its text; I guess `UITextField` does too, at least under some circumstances.)

So I think it's trying to match the text inside the field rather than the cell. But if you typed "shirt" then I don't know why it would find it capitalized... your field doesn't capitalize the text on entry, does it?

**Comment by phatmann** [comment]
The text field does in fact capitalize on entry. As the user types, a list of suggestions appears in a table view below the text field, and these suggestions are also capitalized.  That is why typing "shirt" results in a cell named "SHIRT" appearing. I verified (using Zucchini) that the cell is reachable by name via UIAutomation.

I will see if I can debug the problem from within my app. I will also try to come up with a failing test case in the Subliminal test suite as appropriate.

**Comment by phatmann** [comment]
I know exactly what is going on now. If I change my test to only type "shir"

``` objective-c
 [[SLKeyboard keyboard] typeString:@"shir"];
```

then the test passes. Subliminal thinks I am trying to match the search text field when I look for an element named "SHIRT", since the field contains the text "SHIRT". However, the name of this field is set to "Search Text" via an accessibilityLabel. I verified that

``` javascript
UIATarget.localTarget().frontMostApp().elements()["SHIRT"]
```

is a nil element, and 

``` javascript
UIATarget.localTarget().frontMostApp().tableViews()[0].cells()["SHIRT"]
```

is the cell I am looking for. So it seems to me that Subliminal's behavior is not correct.

Would you like me to author the appropriate failing test case?

**Comment by wearhere** [comment]
Thanks for figuring this out, @phatmann! You're totally right, Subliminal should not be trying to match the text within the field when UIAutomation does not recognize that as a valid element. I've fixed this in the pull request that just went up. We should have it merged within the next day or so.

**Comment by phatmann** [comment]
Glad to have helped, this was a tricky bug. Subliminal is awesome and getting better :-)
