### ISSUE TITLE
testSLWaitUntilTrueDoesNotThrowIfConditionIsStillFalseAtEndOfTimeout accuracy doesn't make sense

### ISSUE THREAD

**Issue by aegolden** [inkling/Subliminal#53]
The test case

testSLWaitUntilTrueDoesNotThrowIfConditionIsStillFalseAtEndOfTimeout

uses an accuracy of 0.01 for the SLWaitUntilTrue:withTimeout: timeout, but the definition of SLWaitUntilTrue waits for an additional 0.25 seconds every time the test expression fails.

So we can reasonably expect at least 0.25 seconds extra time in the worst case.  On the other hand, I don't think we should ever end the timeout even 0.01 seconds early.

**Comment by wearhere** [comment]
You're right, it's a coincidence that I happened to pick a timeout which was cleanly divisible by the retry delay.

I think that you're also right that we shouldn't allow the actual wait to ever drop below the expected wait... this is actually a flaw in all the timeout based tests (both unit and integration)--they all look something like

``` objc
SLAssertTrue(ABS(actualWaitTimeInterval - expectedWaitTimeInterval) < [self waitDelayVariability], …)
```

--oops.

**Comment by wearhere** [comment]
It also looks like `-[SLTerminalTest waitDelayVariability]` doesn't account for the variability in JS execution (i.e. I forgot to update that calculation like I did elsewhere in the project in 2ea104695f10). Sample Travis failure: https://travis-ci.org/inkling/Subliminal/builds/10175832#L1863.
