### ISSUE TITLE
Reproducing test runs.

### ISSUE THREAD

**Issue by wearhere** [inkling/Subliminal#78]
### Goals

To track down [test pollution](http://pivotallabs.com/find-test-pollution-rspec/)

> seemingly false negatives or false positives in a test suite[, occurring] when some shared state is unintentionally modified, or unintentionally read and used in a test

it would be useful to:
1. be able to reproduce failing test runs in the order that the tests ran.
2. (within that run) skip to a particular test--e.g. the last one before the tests started failing, on the theory that that test was the polluter.
### Proposal

Tests are currently run in a pseudorandom order (the order that the runtime discovers them, which I'm pretty sure is the order in which they're linked). This order may be reused across runs but not necessarily.

I propose that we:
- fully randomize test ordering
- if one or more tests fail, log the seed that was used to randomize that run
- allow the tests to be rerun using that seed, thus in a consistent order

This functionality would be exposed to the user via a new API on `SLTestController`:

``` objc
- (void)runTests:(NSSet *)tests usingSeed:(unsigned int)seed withCompletionBlock:(void (^)(void))completionBlock;
```

> Note: `-[NSSet allObjects]` does not return objects in a determinate order, but we would need a consistent basis for randomization. So, I propose that the test controller would alphabetize `[tests allObjects]` before randomizing.

To accomplish goal 2, given a particular set of tests, seed, and test

``` objc
- (void)runTests:(NSSet *)tests usingSeed:(unsigned int)seed skippingToTest:(Class)firstTest withCompletionBlock:(void (^)(void))completionBlock;
```

 the test controller would iterate through the tests, using the predefined order, until `firstTest` was reached, then would begin executing the tests.
### Questions
1. Do we even need both APIs, or would the second suffice?
2. Should these APIs be `DEBUG`-only to prevent them being used in CI environments?

**Comment by aegolden** [comment]
Could we just use the first method and rely on the `focus_` functionality to restrict the tests that run?  For example, I might `focus_` the test before the one that failed and the one that failed, and then I'd like to be able to use `runTests:usingSeed:withCompletionBlock:` and see just those two tests run, but guaranteeing that they run in the same order they did the first time.

We'd have to sort and randomize using the seed, the list of all the tests, then iterate through that list and pick out any `focus_`ed tests, maintaining their relative order.

**Comment by wearhere** [comment]
I like that idea a lot @aegolden. I hadn't actually thought about how focussing would work while tests were seeded but I think that will compose nicely.
